blogs/urls.py
from django.conf.urls import url

from . import views

app_name = 'blogs'
urlpatterns = [

    url(
        r'^$',
        views.BlogsListView.as_view(),
        name='blogs'
    ),
    url(
        r'^(?P<pk>\d+)/create',
        views.PostCreateView.as_view(),
        name = 'create',
    ),

    url(
        r'^(?P<pk>\d+)/(?P<post_id>\d+)/update',
        views.PostUpdateView.as_view(),
        name = 'update',
    ),
    url(
        r'^(?P<pk>\d+)',
        views.PostsListView.as_view(),
        name = 'blog',
    ),


    url(
        r'^(?P<pk>\d+)/subscribe',
        views.SubscribeView.as_view(),
        name = 'subscribe',
    ),

    url(
        r'^unsubscribe/(?P<pk>\d+)',
        views.UnSubscribeView.as_view(),
        name='unsubscribe',
    ),





]

nekidaem_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from blogs import views

urlpatterns = [
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),

    url(
        r'^blogs/',
        include('blogs.urls'),
    ),

    url(r'^admin/',
        admin.site.urls,
        name='admin'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Автор')
    name = models.CharField(max_length=100, verbose_name='Название блога')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'


class Post(models.Model):
    name = models.CharField(max_length=100, verbose_name='Заголовок поста')
    content = models.TextField(max_length=2000, verbose_name='Контент поста')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='Блог')
    creation_time = models.DateTimeField(auto_now_add=True)
    edit_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Subscribe(models.Model):
    class Meta:
        unique_together = (("user", "blog"),)
        verbose_name = 'Подписки'
        verbose_name_plural = 'Подписка'

    user = models.ForeignKey(User ,on_delete=models.CASCADE, verbose_name='Подписанный пользователь', related_name='subscribe')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='Блог', related_name='subscribe')
    readed = models.ManyToManyField(Post, related_name='+')

    def __str__(self):
        return self.user.username + " " + self.blog.name

blogs/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Case, When, BooleanField
from django.http import HttpResponseForbidden, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from blogs.models import Blog, Subscribe, Post


class IndexView(View):
    template = 'blogs/index.html'

    def get(self, request):
        return render(request, self.template)


class BlogsListView(ListView):
    model = Blog
    paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_authenticated:

            blogs_ids = Subscribe.objects.filter(
                user=self.request.user
            ).values_list('blog', flat=True)

            queryset = self.model.objects.annotate(
                has_subscribed=Case(
                    When(pk__in=blogs_ids, then=True),
                    default=False,
                    output_field=BooleanField(),
                ),
            )
        else:
            queryset = self.model.objects.all()

        return queryset


class SubscribeView(CreateView):
    model = Subscribe
    fields = ['blog', 'user']
    success_url = reverse_lazy('blogs:blogs')
    template_name = 'blogs/blog_list.html'

    def dispatch(self, request, *args, **kwargs):
        self.blog = get_object_or_404(Blog, id=kwargs.get('pk'))
        return super(SubscribeView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(SubscribeView, self).get_form_kwargs()
        if self.request.method == 'POST':
            data = dict(kwargs['data'])
            data.update({
                'blog': self.blog.pk,
                'user': self.request.user.pk,
            })
            kwargs['data'] = data
        return kwargs


class UnSubscribeView(DeleteView):
    model = Subscribe
    success_url = reverse_lazy('blogs:blog')
    template_name = 'blogs/blog_list.html'

    def dispatch(self, request, *args, **kwargs):
        self.blog = get_object_or_404(Blog, id=kwargs.get('pk'))
        return super(UnSubscribeView, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        qs = super(UnSubscribeView, self).get_queryset()
        obj = qs.filter(
            user=self.request.user,
            blog=self.blog
        ).first()
        if obj is None:
            raise Http404('Блог не найден')
        return obj


class PostCreateView(CreateView):
    model = Post
    template_name = 'blogs/post_form.html'
    fields = ['name', 'content']

    def dispatch(self, request, *args, **kwargs):
        self.blog = get_object_or_404(Blog, id=kwargs.get('pk'))
        return super(PostCreateView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        print(self.kwargs)
        return reverse('blogs:blog', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        form.instance.blog = self.blog
        return super(PostCreateView, self).form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'blogs/post_form.html'
    fields = ['name', 'content']

    def get_success_url(self):
        print(self.kwargs)
        return reverse('blogs:blog', kwargs={'pk': self.kwargs['pk'], })


class PostsListView(ListView):
    model = Post
    template_name = 'blogs/post_list.html'
    paginate_by = 5

    def get_queryset(self):
        return self.model.objects.select_related('blog').filter(blog=self.blog)

    def dispatch(self, request, *args, **kwargs):
        self.blog = get_object_or_404(Blog, id=kwargs.get('pk'))
        return super(PostsListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super(PostsListView, self).get_context_data(**kwargs)
        context_data['blog'] = self.blog
        return context_data

blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {% block title %}
    <title>Title</title>
    {% endblock %}

</head>
<body>
{% block body %}

    {% include 'navbar.html' %}

     <div class="container">
         {% block content %}
         {% endblock %}
     </div>

{% endblock %}
</body>
</html>

blogs/templates/blogs/blog_list.html
{% extends  'base.html'%}

{% block title %}
    <title>Все блоги</title>
{% endblock %}

{% block content %}
    {% for blog in blog_list %}
        <a href="{%  url 'blogs:blog' pk=blog.id %}"><h2>{{ blog }}</h2></a>

        {% if blog.has_subscribed %}
            <form action="{% url 'blogs:unsubscribe' pk=blog.id %}" method="post">
                {% csrf_token %}
                <button class="btn-danger" type="submit">Отписаться</button>
            </form>

        {% elif user.is_authenticated and blog.owner != user %}
            <form action="{% url 'blogs:subscribe' pk=blog.id %}" method="post">
                {% csrf_token %}
                <button class="btn-success" type="submit">Подписаться</button>
            </form>

        {% elif user.is_authenticated %}
            <p>Это ваш блог</p>
        {% endif %}

    {% endfor %}

    <div class="clearfix"></div>

    {% include 'pagination.html' %}


{% endblock %}

blogs/templates/blogs/index.html
{% extends  'base.html'%}

{% block title %}
    <title>Задание</title>
{% endblock %}

{% block content %}
    <h2>Реализовать бэкенд с минимальным фронтендом (можно на голом HTML):</h2>
    <ol>
        <li>Имеется база стандартных пользователей Django (добавляются через админку, регистрацию делать не надо).</li>
        <li>У каждого пользователя есть персональный блог. Новые создавать он не может;</li>
        <li>Пост в блоге — элементарная запись с заголовком, текстом и временем создания.</li>
        <li>Пользователь может подписываться (отписываться) на блоги других пользователей (любое количество).</li>
        <li>У пользователя есть персональная лента новостей, в которой в обратном хронологическом
            порядке выводятся посты из блогов, на которые он подписан.</li>
        <li>Пользователь может помечать посты в ленте прочитанными.</li>
        <li>При добавлении/удалении подписки содержание ленты меняется (при удалении подписки пометки о "прочитанности" сохранять не нужно).</li>
        <li>При добавлении поста в ленту — подписчики получают почтовое уведомление со ссылкой на новый пост.</li>
        <li>Изменение содержания лент подписчиков (и рассылка уведомлений) должно происходить как при стандартной
            публикации поста пользователем через интерфейс сайта, так при добавлении/удалении поста через админку.</li>
    </ol>
{% endblock %}

blogs/templates/blogs/post_form.html
{% extends  'base.html'%}

{% block title %}
    <title>{% if post %}Редактировать пост{% else %} Создать пост {% endif %}</title>
{% endblock %}

{% block content %}
    <h2>{% if post %}Редактировать пост {{ post.name }}
    {% else %} Создать пост {% endif %}</h2>

    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn-primary">Сохаранить</button>
    </form>
{% endblock %}

blogs/templates/blogs/post_list.html
{% extends  'base.html'%}

{% block title %}
    <title>Блог {{ blog.name }}</title>
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2>{{ blog.owner}}</h2>
        <h2>Блог "{{ blog.name }}"</h2>
    </div>

    <div class="clearfix"></div>

     {% for post in post_list %}
         {% if user == blog.owner %}
            <a href="{% url 'blogs:update' pk=blog.id post_id=post.id %}">
                <h3>{{ post.name }}</h3>
            </a>
        {% endif %}
         <p>{{ post.content }}</p>
         <p>Дата создания {{ post.creation_time }}</p>
    {% endfor %}

    <br>

    {% if user == blog.owner %}
        <a href="{% url 'blogs:create' pk=blog.id %}">Добавить пост</a>
    {% endif %}

    <div class="clearfix"></div>

    {% include 'pagination.html' %}

{% endblock %}

blogs/templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">Тестовый блог</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
          {% if user.is_authenticated %}
             <li><a href="{% url 'blogs:blog' pk=user.blog.id %}">Мой блог</a></li>
          {% endif %}
          <li><a href="{% url 'blogs:blogs' %}">Все блоги</a></li>
          <li><a href="#">Моя лента</a></li>
      </ul>
    </div>
  </div>
</nav>

blogs/templates/pagination.html
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-sm btn-primary">Предыдущая</a>
    {% endif %}

    {% if page_obj.number == 1 and not page_obj.object_list %}
        Пусто
    {% else %}
        Cтраница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
    {% endif %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-sm btn-primary">Следующая</a>
    {% endif %}

</div>